### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by justdark** [HessianZ/daisy-proxy#1]
话说能详细一点吗，出口ip就是脸上vpn之后的那个10.开头的ip吗，我用的时候一直说我没指定IP啊，是-ip 10.0.0.6这样吗~~多谢解答

**Comment by HessianZ** [comment]
是的，出口IP就是VPN给你分配的IP地址，也可以用-if 直接指定网卡设备名，省的每次查IP。

## 

Hessian
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)
