### ISSUE TITLE
页面报错

### ISSUE THREAD

**Issue by dearneo** [HessianZ/daisy-proxy#2]
环境：win7 64bit；vpn已连上，取消了在远程网络上使用默认网关选项。
软件运行配置：daisy-proxy.exe -ip="10.0.4.7" 
DaisyProxy listen on localhost:8080 outgoing from 10.0.4.7

网页页面显示如下字样，未被墙和被墙网页均打不开。
dial tcp 206.213.249.32:80: ConnectEx tcp: A socket operation was attempted to an unreachable network.

**Comment by HessianZ** [comment]
这个情况好像没有遇到过。首先确认程序没有被防火墙阻挡，然后尝试一下通过你的VPN地址去ping一个外网地址：ping -S 10.0.4.7 206.213.249.32 看看你的VPN连接是不是正常。这种情况像是路由有问题。
